CREATE OR REPLACE FUNCTION UuidToBin(_uuid BINARY(36))
    RETURNS BINARY(16)
    LANGUAGE SQL  DETERMINISTIC  CONTAINS SQL  SQL SECURITY INVOKER
    RETURN
        UNHEX(REPLACE(_uuid, '-', ''));


CREATE OR REPLACE FUNCTION UuidFromBin(_bin BINARY(16))
RETURNS BINARY(36)
LANGUAGE SQL  DETERMINISTIC  CONTAINS SQL  SQL SECURITY INVOKER
RETURN
    LCASE(CONCAT_WS('-',
         SUBSTR(HEX(_bin), 1, 8),
         SUBSTR(HEX(_bin), 9, 4),
         SUBSTR(HEX(_bin), 13, 4),
         SUBSTR(HEX(_bin), 17, 4),
         SUBSTR(HEX(_bin), 21)

));